
services:
  app:
    env_file: 
      - .env
    build: 
      args:
        - HF_AUTH_TOKEN
        - HF_HOME=/huggingface
      context: .
    volumes:
      - .:/workdir
      - /home/tornikeo/.cache/huggingface:/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]