name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NAME: ${{ github.event.repository.name }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        NAME: ${{ github.event.repository.name }}
      run: |
        DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag $DOCKER_USER/$NAME
        docker tag $DOCKER_USER/$NAME $DOCKER_USER/$NAME:$(date +%s)
        docker tag $DOCKER_USER/$NAME $DOCKER_USER/$NAME:latest
    - name: Docker Push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        NAME: ${{ github.event.repository.name }}
      run: |
        docker push --all-tags $DOCKER_USER/$NAME
